### PR TITLE
useful tips on loading ext while running

### PR DESCRIPTION
**Pull request by mwic**
Might make yr life easier

### CODE REVIEW

**Comment by groovecoder** [comment]
I (think I) got the extension auto-installer stuff working, but I'm having a hard time debugging errors. Where does the console.log output show up in this setup? Doesn't seem to show in the firefox dev tools console ...

**Comment by mwic** [comment]
It's in the terminal in which you did CFX run ..

**Comment by groovecoder** [comment]
CFC run? You mean cfx run? So I have to do cfx run with a profile with the auto-installer, and then run this?

**Comment by mwic** [comment]
yes, one terminal tab will have the cfx, another will have the wget loop

**Pull request merged**
