### PR TITLE
mwic Generalized codesy addon, supports multiple sites if you do just a bit of work setting them up

### PR DESCRIPTION
**Pull request by mwic**
I know everyone uses github. I also remember in 2006 when clients would run me down a bit because "everyone uses IE"

the enable-site prefs are really hacky and hopefully can be fixed if simple-prefs gets a proper multiselect form type someday. For now we roll with a bit of eval/evil

Here's Christina Rossetti's poem "In the Bleak Midwinter",  'cause it seems appropriate tonight

```
In the bleak mid-winter 
```

 Frosty wind made moan, 
 Earth stood hard as iron, 
 Water like a stone;
 Snow had fallen, snow on snow,
 Snow on snow, 
 In the bleak mid-winter 
 Long ago.

```
Our God, Heaven cannot hold Him 
```

 Nor earth sustain; 
 Heaven and earth shall flee away 
 When He comes to reign: 
 In the bleak mid-winter 
 A stable-place sufficed 
 The Lord God Almighty, 
 Jesus Christ.

```
Enough for Him, whom cherubim 
```

 Worship night and day, 
 A breastful of milk 
 And a mangerful of hay; 
 Enough for Him, whom angels 
 Fall down before, 
 The ox and ass and camel 
 Which adore.

```
Angels and archangels 
```

 May have gathered there, 
 Cherubim and seraphim 
 Thronged the air, 
 But only His mother 
 In her maiden bliss, 
 Worshipped the Beloved 
 With a kiss.

```
What can I give Him, 
```

 Poor as I am? 
 If I were a shepherd 
 I would bring a lamb, 
 If I were a wise man 
 I would do my part, 
 Yet what I can I give Him, 
 Give my heart.

### CODE REVIEW

**Comment by mwic** [comment]
Well I got a comment regarding the limitation of simple-prefs, but it's almost all over my head (for now):
https://forums.mozilla.org/addons/viewtopic.php?f=7&t=15482
Splitting the string on the underscore and getting the site-specific data that way works, but isn't ideal. Accept this PR and let me know what approach should be taken, and I'll buttress it up next round.

**Comment by groovecoder** [comment]
I like putting the form HTML up into a variable that can be re-used. To do this, we should move most of the code up to be re-used across sites.

Should we really ask about every site? I think we should simply add the form to every site we can.

Needs a re-base on master now that the codesy domain list PR has been merged.

**Comment by mwic** [comment]
I could definitely picture a set of options like this (radio buttons)
Add codesy to:
- the usual sites (would be the 5-6 most relevant and well-tested partners)
- literally every site I visit (pageMod would use data/codesy.js and codesy.css , maybe appending to the < body > tag?) 
- customized list of sites (expands into the checkboxes I have in this PR)

**Comment by groovecoder** [comment]
FWIW, https://github.com/codesy/chrome-extension/pull/8 has a good approach to creating a more generic codesy.js to contain the API calls.

**Pull request merged**
